[build]
  command = "npm install && npm run build"
  functions = "functions/"

[functions.render]
  external_node_modules = ["chrome-aws-lambda"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
